name: OpenXR Feature Manager

on:
  push:
    paths:
    - .github/workflows/build-openxr-feature-manager.yml
    - OpenXRFeatureManager/**
    - ExtraOpenXRFeatures.sln
    branches:
    - '**'
    tags:
    - openxr-feature-manager/*

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4

    - name: Set up Beat Saber
      uses: nicoco007/setup-beat-saber@main
      with:
        access-token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
        manifest: ${{ github.workspace }}\OpenXRFeatureManager\manifest.json
        tag-format: openxr-feature-manager/v{0}

    - name: Add NuGet source
      run: dotnet nuget update source "nicoco007 GitHub Packages" --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

    - name: Build Release
      id: build-release
      run: dotnet build ${{ github.workspace }}\OpenXRFeatureManager\OpenXRFeatureManager.csproj -c Release

    - name: Upload Release
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build-release.outputs.artifact-name }}
        path: ${{ steps.build-release.outputs.artifact-path }}
